x-service-templates:
  app: &app
    image: gaoliveira21/rinha2025-node:latest
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "90MB"

services:
  nginx:
    image: nginx:1.29-alpine
    container_name: rinha-node-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
      - app02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  redis:
    image: redis:7.2-alpine
    container_name: redis-db
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  app01:
    <<: *app
    container_name: rinha-node-app01
    hostname: app01
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - REDIS_URL=redis://redis:6379
      - REDIS_PREFIX=rinha-node-app01
    depends_on:
      redis:
        condition: service_healthy

  app02:
    <<: *app
    container_name: rinha-node-app02
    hostname: app02
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - REDIS_URL=redis://redis:6379
      - REDIS_PREFIX=rinha-node-app02
    depends_on:
      redis:
        condition: service_healthy

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
